camera_0:
  camera_info_url: "file:///home/visnet/catkin/src/visnet/camera_info/camera_0.yaml"
  device_id: 0
  cv_cap_prop_fps: 30
  # cv_cap_prop_fourcc: 1735420525 # mjgp
  # cv_cap_prop_fourcc: 1196444237 # MJPG
  cv_cap_prop_gain: 64
  cv_cap_prop_brightness: 30
  cv_cap_prop_hue: 0
  cv_cap_prop_auto_exposure: 3 # 1-manual 3-aperture priority
  # cv_cap_prop_exposure: 9000

camera_1:
  camera_info_url: "file:///home/visnet/catkin/src/visnet/camera_info/camera_1.yaml"
  device_id: 0
  cv_cap_prop_fps: 30
  # cv_cap_prop_fourcc: 1735420525 # mjgp
  # cv_cap_prop_fourcc: 1196444237 # MJPG
  cv_cap_prop_gain: 64
  cv_cap_prop_brightness: 30
  cv_cap_prop_hue: 0
  cv_cap_prop_auto_exposure: 3 # 1-manual 3-aperture priority
  # cv_cap_prop_exposure: 9000

camera_2:
  camera_info_url: "file:///home/visnet/catkin/src/visnet/camera_info/camera_2.yaml"
  device_id: 0
  cv_cap_prop_fps: 30
  # cv_cap_prop_fourcc: 1735420525 # mjgp
  # cv_cap_prop_fourcc: 1196444237 # MJPG
  cv_cap_prop_gain: 64
  cv_cap_prop_brightness: 30
  cv_cap_prop_hue: 0
  cv_cap_prop_auto_exposure: 3 # 1-manual 3-aperture priority
  # cv_cap_prop_exposure: 9000

camera_3:
  camera_info_url: "file:///home/zpyang/git/visnet/src/visnet/camera_info/camera_3.yaml"
  device_id: 0
  cv_cap_prop_fps: 30
  # cv_cap_prop_fourcc: 1735420525 # mjgp
  # cv_cap_prop_fourcc: 1196444237 # MJPG
  cv_cap_prop_gain: 64
  cv_cap_prop_brightness: 30
  cv_cap_prop_hue: 0
  cv_cap_prop_auto_exposure: 3 # 1-manual 3-aperture priority
  # cv_cap_prop_exposure: 9000